# docker-compose.yml

version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    command: ffmpeg -re -stream_loop -1 -i /examples/fall_detection_1.mp4 -c copy -f rtsp rtsp://localhost:8554/mystream
    ports:
      - "8554:8554"
      - "8888:8888" # If you need the admin interface
    restart: unless-stopped

  app:
    build: ./app
    container_name: app
    depends_on:
      - mediamtx
      - ffmpeg
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    restart: unless-stopped
